name: DevSecOps

on:
  workflow_dispatch:
    inputs:
      testing:
        type: choice
        options:
          - DevOps
          - SAST/SCA
          - DAST/IAST
        required: true  

jobs:
  secret-leaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: trufflehog-actions-scan
      run: docker run --rm -t -v "$PWD:/pwd" trufflesecurity/trufflehog:latest  filesystem /pwd/lib/
      
  
  build:
    runs-on: ubuntu-latest
    needs: secret-leaks
    steps:
      - name: "npm build"
        run: echo "Build complete"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Execute unit tests and smoke tests"
        run: echo "Test complete"

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare Docker image"
        run: echo "Image pushed"


  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: "Trigger deployment"
        run: echo "Deployed successfully"
